Feat/cluster
topfreegames/kubecos pull request #3
Opened 2017-04-05 16:57 UTC by Henrod

2017-04-05 22:21 UTC, felipejfc requested changes

2017-04-05 22:21 UTC, felipejfc commented on migrations/0002-CreateClusterTable.sql
> +    apps JSONB NOT NULL DEFAULT '{}'::JSONB,
acho que vale a pena guardar o yaml tb como string

2017-04-06 04:54 UTC, felipejfc approved these changes

2017-04-06 04:55 UTC, merged

2017-04-06 13:09 UTC, Henrod commented on migrations/0002-CreateClusterTable.sql
> +    apps JSONB NOT NULL DEFAULT '{}'::JSONB,
Na verdade, a melhor solução é guardar apenas o string mesmo. Já está alterado.